name: language_reference_rust

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/language_reference_rust.yml"
      - "language_reference/languages/rust"

jobs:
  language_check_rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: rust
        run: docker compose --project-directory language_reference up --build rust
