name: language_reference_csharp

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/language_reference_csharp.yml"
      - "language_reference/languages/csharp"

jobs:
  language_check_csharp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: csharp
        run: docker compose --project-directory language_reference up --build csharp
