name: language_reference_lua

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/language_reference_lua.yml"
      - "language_reference/languages/lua/**"

jobs:
  language_check_lua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: lua
        run: docker compose --project-directory language_reference up --build lua
