name: language_reference_javascript

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/language_reference_javascript.yml"
      - "language_reference/languages/javascript"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: javascript
        run: docker compose --project-directory language_reference up --build javascript
