name: language_reference_vb

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/language_reference_vb.yml"
      - "language_reference/languages/vb/**"

jobs:
  language_check_vb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: vb
        run: docker compose --project-directory language_reference up --build vb
