name: language_reference_golang

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/language_reference_golang.yml"
      - "language_reference/languages/golang/**"

jobs:
  language_check_golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: golang
        run: docker compose --project-directory language_reference up --build golang
